### ISSUE TITLE
Newest DSPS-HIV Repository?

### ISSUE THREAD

**Issue by niemasd** [PangeaHIV/DSPS-HIV_PANGEA#1]
I am trying to simulate epidemics under the small village model described in the PANGEA paper, but I'm having trouble getting things to run. From the README:

> Please note that this code is archived to reflect what was used to create the simulations used in the PANGEA_HIV comparision exercise, and will not be updated. A seperate DSPS-HIV repository will soon be created where the newest version of the code can be found.

Where can can I find this separate DSPS-HIV repository with the newest version of the code?

**Comment by emmahodcroft** [comment]
Hi Niema,
Unfortunately there is no newer version of the DSPS-HIV that's publicly available at the moment. Sorry about that!

**Comment by niemasd** [comment]
No worries, thanks!
