### ISSUE TITLE
viralLoads.txt and newMaxTime.txt

### ISSUE THREAD

**Issue by niemasd** [PangeaHIV/DSPS-HIV_PANGEA#2]
It seems like the simulator depends on two key files: `viralLoads.txt` and `newMaxTime.txt`. In the hardcoded paths, these files were located at `C:\Users\Room65-Admin\Desktop\Emma\viralLoads.txt` and `C:\Users\Room65-Admin\Desktop\Emma\newMaxTime.txt`, respectively, but I don't see them anywhere in this repository. Where can I find these two files?

**Comment by emmahodcroft** [comment]
Hi Niema. `viralLoads.txt` is the collection of log viral loads you would like the DSPS-HIV to sample from during the simulation. I can't upload my file as it's from the UK HIV DRB, but you could generate your own distribution of viral loads for the population you're trying to simulate, or use data you might already have. The file has the format of are one log viral load per line.

`newMaxTime.txt` is a simple file that just contains the maximum time you want the simulation to run. You can have it be blank if you want to stick to whatever you set in the XML, but the simulator will check it periodically to see if it contains a max time different from what was set in the XML, and will change the run if a new time is found. This is handy if you decide you want to end a simulation early for any reason, as it allows the simulation to finish cleanly and write out all output/files. 

You can get a little more info about both files in 2.1 of the readme.

**Comment by niemasd** [comment]
Thanks for the information!
